
package vista;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import olc1_ptc1_201500332.AnalizadorLex;
import olc1_ptc1_201500332.AnalizadorSint;
import olc1_ptc1_201500332.Archivo;
import olc1_ptc1_201500332.Siguiente;
import olc1_ptc1_201500332.Transicion;

/**
 *
 * @author OLGA BARRIOS
 */
public class Ventana extends javax.swing.JFrame {

    JFileChooser choose = new JFileChooser();
    File archivo;
    Archivo arch = new Archivo();
    AnalizadorLex analizador = new AnalizadorLex();
    AnalizadorSint sintac = new AnalizadorSint();
    Siguiente siguiente = new Siguiente("", 0);
    Transicion trans = new Transicion();
    public Ventana() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtconsola = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxterror = new javax.swing.JTextArea();
        btanalizar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtconsola.setColumns(20);
        jtxtconsola.setRows(5);
        jScrollPane1.setViewportView(jtxtconsola);

        jtxterror.setColumns(20);
        jtxterror.setRows(5);
        jScrollPane3.setViewportView(jtxterror);

        btanalizar.setText("Analizar");
        btanalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btanalizarActionPerformed(evt);
            }
        });

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir Archivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Documentacion");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");

        jMenuItem3.setText("Ver arbol");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Ver Siguientes");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Ver Transiciones");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Ver AFD");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btanalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btanalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(choose.showDialog(this, "Abrir Archivo")== JFileChooser.APPROVE_OPTION){
            archivo = choose.getSelectedFile();
            if(archivo.canRead()){
                if(archivo.getName().endsWith("er")){
                    String texto = arch.Abrir(archivo);
                    jtxtconsola.setText(texto);
                }
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btanalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btanalizarActionPerformed
        String analisis = analizador.analizar(jtxtconsola);
        String graf="";
        if(!analizador.error){
            analisis =  sintac.obtenerDatos(analizador.tokens);
            jtxterror.setText(analisis + "\n");
            Conjunto conj = new Conjunto("", "");
            DefExpresion def = new DefExpresion("", 0);
            ArrayList<ArrayList> tabla = new ArrayList();
            String cad = "";
            if(!sintac.mal){
                graf = conj.imprimirConjuntos(sintac.conjunto);
                def.terminarPosiciones(sintac.defexpresion);
                try {
                    arch.generarGrafica(graf,"Conjuntos","Conjs");
                    for (int i = 0; i < sintac.defexpresion.size(); i++) {
                        sintac.transiciones.clear();
                        tabla.clear();
                        cad = sintac.expre.get(i).toString();
                        graf = def.dibujarExpresion(sintac.defexpresion.get(i));
                        arch.generarGrafica(graf, cad,cad);
                        siguiente.darSiguienteRaiz(sintac.defexpresion.get(i),sintac.defexpresion.get(i).hojas);
                        graf = siguiente.dibujarSiguientes(sintac.defexpresion.get(i).hojas);
                        arch.generarGrafica(graf, cad + "Sigs",cad);
                        sintac.transiciones = trans.darEstado(sintac.defexpresion.get(i));
                        trans.darTransicion(sintac.transiciones, sintac.defexpresion.get(i).hojas);
                        graf = trans.dibujarTransicion(sintac.transiciones, sintac.defexpresion.get(i).hojas);
                        arch.generarGrafica(graf, cad + "Transiciones",cad);
                        graf = trans.crearAFD(sintac.transiciones);
                        arch.generarGrafica(graf, cad + "AFD", cad);
                        for (int j = 0; j < sintac.expre.size() ; j++) { 
                            for (int k = 0; k < sintac.expresion.size(); k++) {
                                if(sintac.expresion.get(k).id.equalsIgnoreCase(sintac.expre.get(j).toString())){
                                    jtxterror.setText(jtxterror.getText() + "Expresion: " + sintac.expresion.get(k).id + ": " + trans.reconocerLexema(sintac.transiciones, sintac.expresion.get(k).exp) + "\n");
                                }
                            }
                        }
                    }
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, analisis);
            for (int i = 0; i < analizador.tokens.size(); i++) {
                jtxterror.setText(jtxterror.getText() + analizador.tokens.get(i).getLexema() + " ") ;
            }
        }
    }//GEN-LAST:event_btanalizarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        jtxtconsola.setText("");
        jtxterror.setText("");
    }//GEN-LAST:event_btnlimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btanalizar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jtxtconsola;
    private javax.swing.JTextArea jtxterror;
    // End of variables declaration//GEN-END:variables
}
